apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-redis-said 
  labels:
    app: node-redis-said 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-said
  template:
    metadata:
      labels:
        app: redis-said
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: node-redis-regcred
          image: cloud.canister.io:5000/arhturescriou/node-redis
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: '6379'
            - name: REDIS_URL
              value: 'redis://10.3.16.40'
